#!/usr/bin/env python3
"""Command-line integration for gdextest consumers."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

from gdextest_config import (
    Config,
    discover_sources,
    find_project_root,
    godot_cpp_version,
    godot_executable,
    godot_version,
    load_config,
    locate_extension_library,
    locate_extension_manifest,
)


CONFIG_TEMPLATE = '''[gdextest]
version = "1"
godot_version = "4.5"

[gdextest.tests]
sources = ["tests/**/*.cpp"]

[gdextest.host]
mode = "editor"
entry_symbol = "gdextest_library_init"
plugin_class = "GdextestPlugin"

[gdextest.test]
timeout_ms = 30000
isolate_timeout_sec = 60
flaky_retries = 3

[gdextest.fixture]
directory = "build/gdextest/project"
project_name = "gdextest fixture"
native_extensions = []
assets = []
scan_timeout_ms = 20000

[gdextest.output]
directory = "bin"
name = "libgdextest"

[gdextest.build]
args = []
'''

CI_TEMPLATE = '''name: gdextest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install SCons
        run: python3 -m pip install scons
      - name: Download Godot 4.5
        run: |
          curl -fsSL -o godot.zip https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          unzip -o godot.zip
          chmod +x Godot_v4.5-stable_linux.x86_64
      - name: Run gdextest
        run: python3 extern/gdextest/tools/gdextest.py test --godot "$GITHUB_WORKSPACE/Godot_v4.5-stable_linux.x86_64"
'''

# Scaffolded GDExtension entry (mirrors src/gdextest_entry.cpp). The plugin
# class name and entry symbol come from .gdextest.toml so the generated fixture
# wrapper instantiates exactly the class the entry registers. @PLUGIN_CLASS@ and
# @ENTRY_SYMBOL@ are replaced with str.replace so template braces stay literal.
ENTRY_TEMPLATE = '''// GDExtension entry + EditorPlugin shell generated by `gdextest scaffold`.
// The plugin class and entry symbol are sourced from .gdextest.toml
// ([gdextest.host] plugin_class / entry_symbol). Test build only.
#ifdef GDEXTEST_ENABLED

#include <godot_cpp/classes/editor_plugin.hpp>
#include <godot_cpp/godot.hpp>

namespace gdextest_adapter { void maybe_run(godot::Node *tree_node); }

class @PLUGIN_CLASS@ : public godot::EditorPlugin {
    GDCLASS(@PLUGIN_CLASS@, godot::EditorPlugin)

protected:
    static void _bind_methods() {
        godot::ClassDB::bind_method(godot::D_METHOD("_run_tests"),
                                    &@PLUGIN_CLASS@::_run_tests);
    }

public:
    void _ready() override {
        call_deferred("_run_tests");
    }

    void _run_tests() {
        gdextest_adapter::maybe_run(this);
    }
};

using namespace godot;

void initialize_test_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_EDITOR) return;
    ClassDB::register_class<@PLUGIN_CLASS@>();
}

void uninitialize_test_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_EDITOR) return;
}

extern "C" {

GDExtensionBool GDE_EXPORT @ENTRY_SYMBOL@(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        const GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization) {
    godot::GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library,
                                                   r_initialization);
    init_obj.register_initializer(&initialize_test_module);
    init_obj.register_terminator(&uninitialize_test_module);
    init_obj.set_minimum_library_initialization_level(
            godot::MODULE_INITIALIZATION_LEVEL_EDITOR);
    return init_obj.init();
}

}  // extern "C"

#endif // GDEXTEST_ENABLED
'''

SMOKE_SUITE = '''// Smoke suite generated by `gdextest scaffold`.
#include "gdextest/assert.h"
#include "gdextest/registry.h"

GDEX_TEST(smoke, framework_is_wired) {
    GDEX_EXPECT(true);
}
'''

SCONSTRUCT_SNIPPET = '''
# --- gdextest test framework (scaffolded) ---
lib = env.SConscript(
    "extern/gdextest/SConscript",
    variant_dir="build/gdextest", duplicate=0,
    exports={"env": env, "gdextest": {
        "entry": "testsupport/entry.cpp",
    }},
)
if lib:
    Default(lib)
'''

# Appended to a temporary copy of the consumer's SConstruct when it is not
# wired, so `gdextest test` can build without modifying the real build file.
# scons -f <file> makes the copy act as the SConstruct; the copy lives in the
# project root so `#`-anchored paths and variant_dir keep resolving the same.
# The framework call stays minimal: entry/adapter default to the framework's
# own, and the CLI's gdextest_* env vars drive suites/host mode from the TOML.
SCONSTRUCT_INJECTION = '''
# --- gdextest test framework (temporary injection) ---
# This block was appended to a temporary copy of your SConstruct so the test
# library can build without touching your real build file. Run
# `gdextest scaffold --apply` to make the wiring permanent.
gdextest_lib = env.SConscript(
    "extern/gdextest/SConscript",
    variant_dir="build/gdextest", duplicate=0,
    exports={"env": env},
)
if gdextest_lib:
    Default(gdextest_lib)
'''


def _framework_path(config: Config) -> str:
    return str(config.framework_dir)


def _scons_command(config: Config) -> list[str]:
    return ["scons", "tests=true", *config.build_args]


def _library_path(config: Config) -> Path | None:
    """Locate the built test library, or None if the SConscript did not run."""
    output = config.project_root / config.out_dir
    if not output.is_dir():
        return None
    candidates = sorted(output.glob(config.out_name + "*"))
    return candidates[0] if candidates else None


def _run_build(config: Config) -> None:
    sources = discover_sources(config)
    if not sources:
        raise RuntimeError("no test sources found; check [gdextest.tests].sources")
    errors = config.validate()
    if errors:
        raise RuntimeError("configuration is invalid:\n  " + "\n  ".join(errors))
    env = os.environ.copy()
    env["gdextest_PROJECT_ROOT"] = str(config.project_root)
    env["gdextest_FRAMEWORK_DIR"] = _framework_path(config)
    env["gdextest_SOURCES"] = os.pathsep.join(
        str(path.relative_to(config.project_root)) for path in sources)
    env["gdextest_HOST_MODE"] = config.host_mode
    if config.bootstrap:
        env["gdextest_BOOTSTRAP"] = config.bootstrap
    command = _scons_command(config)
    injected = None
    sconstruct = config.project_root / "SConstruct"
    if sconstruct.is_file() and not _sconstruct_wired(config.project_root):
        # Unwired repo: build through a temporary SConstruct with the framework
        # call injected, so `gdextest test` works without touching the consumer's
        # build file. Cleaned up in a finally; `scaffold --apply` makes it
        # permanent. Consumers with a custom entry/adapter still use scaffold.
        injected = config.project_root / "SConstruct.gdextest"
        injected.write_text(
            sconstruct.read_text(encoding="utf-8", errors="replace").rstrip()
            + "\n" + SCONSTRUCT_INJECTION,
            encoding="utf-8")
        command = ["scons", "-f", str(injected), "tests=true", *config.build_args]
        print("gdextest: SConstruct not wired — building via a temporary "
              "SConstruct.gdextest; run `gdextest scaffold --apply` to wire it "
              "permanently", flush=True)
    try:
        subprocess.run(command, cwd=config.project_root, env=env, check=True)
    finally:
        if injected:
            injected.unlink(missing_ok=True)
    if not _library_path(config):
        raise RuntimeError(
            f"the test library was not produced (expected {config.out_dir}/{config.out_name}*); "
            "your SConstruct does not appear to call extern/gdextest/SConscript — "
            "run `gdextest scaffold --apply` to wire it")


def _mode_args(config: Config) -> list[str]:
    return ["--headless", "--editor"] if config.host_mode == "editor" else ["--headless"]


def _godot_command(config: Config, executable: str, *user_args: str) -> list[str]:
    return [executable, *_mode_args(config), "--path", str(config.fixture_path), "--",
            "--gdextest-run", *user_args]


def _warm_fixture(config: Config, executable: str) -> None:
    """Run Godot once against a freshly generated fixture to build its cache.

    Godot 4.5's first headless-editor run on a project with no `.godot` cache
    intermittently aborts during cold-start shutdown (SIGSEGV/abort, exit 134 —
    the race documented in testing/notes.md §5). The import completes before
    the abort and the cache is valid afterwards, so a single no-trigger warmup
    pass makes the real run deterministic — without it, a consumer's *first*
    `gdextest test` on a fresh checkout aborts with a confusing backtrace.
    """
    if (config.fixture_path / ".godot").is_dir():
        return
    print("gdextest: warming the fixture's first-run Godot cache "
          "(cold-start shutdown quirk; harmless)", flush=True)
    command = [executable, *_mode_args(config), "--path", str(config.fixture_path),
               "--quit-after", "2"]
    # The warmup is expected to abort (exit 134) on a cold cache; the real run
    # below is the actual pass/fail signal.
    subprocess.run(command, cwd=config.project_root, env=_run_environment(config),
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def _run_environment(config: Config) -> dict[str, str]:
    environment = os.environ.copy()
    user_data = config.project_root / config.build_dir / "user-data"
    # user:// must be hermetic across runs: residue from a previous run (session
    # files, temp repos) would leak into "should not exist at start" assertions.
    if user_data.exists():
        shutil.rmtree(user_data)
    user_data.mkdir(parents=True)
    environment["XDG_DATA_HOME"] = str(user_data)
    return environment


def _print_check(label: str, value: str, ok: bool) -> bool:
    print(f"{'[ok]' if ok else '[!!]'} {label}: {value}", flush=True)
    return ok


def _write_junit(results: list[dict], path: str) -> None:
    """Serialize gdextest results (the JSON `results` array) as JUnit XML.

    GitHub Actions and other CI surfaces render JUnit natively, so the same
    pass/fail/skipped/crashed data becomes inline annotations.
    """
    tests = len(results)
    failures = sum(1 for result in results if result.get("status") in ("fail", "crashed"))
    skipped = sum(1 for result in results if result.get("status") == "skipped")
    suites = ET.Element("testsuites", {"tests": str(tests),
                                        "failures": str(failures),
                                        "skipped": str(skipped)})
    suite = ET.SubElement(suites, "testsuite", {"name": "gdextest",
                                                 "tests": str(tests),
                                                 "failures": str(failures),
                                                 "skipped": str(skipped)})
    for result in results:
        case = ET.SubElement(suite, "testcase", {
            "classname": result.get("suite", ""),
            "name": result.get("name", ""),
            "time": f"{result.get('duration_ms', 0) / 1000.0:.3f}",
        })
        if result.get("status") in ("fail", "crashed"):
            message = "; ".join(
                f"{failure.get('file', '')}:{failure.get('line', 0)} "
                f"{failure.get('message', '')}"
                for failure in result.get("failures", [])) or "test failed"
            ET.SubElement(case, "failure", {"message": message}).text = message
        elif result.get("status") == "skipped":
            ET.SubElement(case, "skipped",
                          {"message": result.get("reason", "")}).text = result.get("reason", "")
    ET.ElementTree(suites).write(path, encoding="utf-8", xml_declaration=True)


def _json_to_junit(json_path: str, junit_path: str) -> None:
    with open(json_path, encoding="utf-8") as handle:
        document = json.load(handle)
    _write_junit(document.get("results", []), junit_path)


def _load_result_documents(patterns: list[str]) -> list[dict]:
    """Load the JSON result documents named by files or glob patterns."""
    documents: list[dict] = []
    for pattern in patterns:
        if any(char in pattern for char in "*?["):
            paths = sorted(Path().glob(pattern))
        else:
            paths = [Path(pattern)]
        for path in paths:
            if not path.is_file():
                raise RuntimeError(f"result file not found: {path}")
            with open(path, encoding="utf-8") as handle:
                documents.append(json.load(handle))
    if not documents:
        raise RuntimeError("no result files matched")
    return documents


def _merge_documents(documents: list[dict]) -> dict:
    """Merge shard result documents: concatenate results, recompute totals."""
    results: list[dict] = []
    for document in documents:
        results.extend(document.get("results", []))
    totals = {"pass": 0, "fail": 0, "skip": 0, "crashed": 0}
    for result in results:
        status = result.get("status")
        if status == "crashed":
            totals["crashed"] += 1
            totals["fail"] += 1
        elif status == "fail":
            totals["fail"] += 1
        elif status == "skipped":
            totals["skip"] += 1
        else:
            totals["pass"] += 1
    return {"totals": totals, "results": results}


def _write_config(root: Path, *, force: bool = False) -> bool:
    """Create the starter config without replacing consumer changes by default."""
    config_path = root / ".gdextest.toml"
    if config_path.exists() and not force:
        print(f"gdextest: keeping existing {config_path}")
        return False
    config_path.write_text(CONFIG_TEMPLATE, encoding="utf-8")
    print(f"gdextest: wrote {config_path}")
    return True


def _sconstruct_wired(root: Path) -> bool:
    """True when the SConstruct calls the framework SConscript.

    A bare `gdextest` string is not enough — consumers that wire godot-cpp
    through the framework's nested submodule mention gdextest in paths without
    calling the SConscript. Look for the documented call site instead.
    """
    sconstruct = root / "SConstruct"
    if not sconstruct.is_file():
        return False
    content = sconstruct.read_text(encoding="utf-8", errors="replace")
    # The documented consumer pattern, or the framework's own relative call
    # (this repo's SConstruct wires `env.SConscript("SConscript", ...)`).
    return "gdextest/SConscript" in content or '"SConscript"' in content


def _run_doctor(config: Config, godot_override: str | None,
                allow_injection: bool = False) -> int:
    """Run the environment checks shared by `doctor` and every test run.

    With `allow_injection`, an unwired SConstruct is reported as an informational
    note instead of a failure: `gdextest test` builds through a temporary
    injected SConstruct in that case.
    """
    print("gdextest doctor", flush=True)
    print(f"project root: {config.project_root}", flush=True)
    print(f"framework:    {config.framework_dir}", flush=True)
    print(f"host mode:    {config.host_mode}", flush=True)
    source_count = len(discover_sources(config))
    print(f"test sources: {source_count}", flush=True)

    ok = True
    errors = config.validate()
    if not errors and not source_count:
        errors.append("no test sources found; check [gdextest.tests].sources")
    ok &= _print_check("configuration", "valid" if not errors else "; ".join(errors), not errors)
    try:
        executable = godot_executable(config, godot_override)
        version = godot_version(executable)
        expected = ".".join(config.godot_version.split(".")[:2])
        ok &= _print_check("Godot", f"{executable} ({version})", version.startswith(expected))
    except (FileNotFoundError, OSError) as error:
        ok &= _print_check("Godot", str(error), False)
    scons = shutil.which("scons")
    ok &= _print_check("SCons", scons or "not found", scons is not None)
    framework_sconscript = config.framework_dir / "SConscript"
    ok &= _print_check("framework SConscript", str(framework_sconscript),
                       framework_sconscript.is_file())
    cpp_version = godot_cpp_version(config.project_root)
    expected_cpp = ".".join(config.godot_version.split(".")[:2])
    if cpp_version is None:
        print("[..] godot-cpp: not found at extern/godot-cpp (binding version unverified)",
              flush=True)
    elif cpp_version == expected_cpp:
        ok &= _print_check("godot-cpp", f"{cpp_version} (matches)", True)
    else:
        print(f"[!!] godot-cpp: {cpp_version} does not match the framework's {expected_cpp} "
              f"(the framework uses {expected_cpp}-only GDExtension APIs); "
              "the test build may fail to compile", flush=True)
    sconstruct = config.project_root / "SConstruct"
    if sconstruct.is_file():
        content = sconstruct.read_text(encoding="utf-8", errors="replace")
        if "gdextest/SConscript" in content or '"SConscript"' in content:
            ok &= _print_check("SConstruct wiring", "gdextest SConscript referenced", True)
        elif "gdextest" not in content and "SConscript" not in content:
            if allow_injection:
                print("[..] SConstruct wiring: not wired — gdextest test will build via a "
                      "temporary SConstruct.gdextest; `gdextest scaffold --apply` wires "
                      "it permanently", flush=True)
            else:
                ok &= _print_check(
                    "SConstruct wiring",
                    "no gdextest/SConscript reference; SConstruct must call "
                    "extern/gdextest/SConscript — run `gdextest scaffold --apply` "
                    "to wire it", False)
        else:
            print("[..] SConstruct wiring: SConscript/gdextest mentioned but no "
                  "extern/gdextest/SConscript call; verify the framework SConscript "
                  "is wired — run `gdextest scaffold --apply` to wire it", flush=True)
    else:
        ok &= _print_check("SConstruct wiring", "SConstruct not found", False)
    extension_library = locate_extension_library(config)
    extension_manifest = locate_extension_manifest(config)
    if extension_library or extension_manifest:
        ok &= _print_check("consumer extension library", str(extension_library),
                           bool(extension_library and extension_library.is_file()))
        ok &= _print_check("consumer extension manifest", str(extension_manifest),
                           bool(extension_manifest and extension_manifest.is_file()))
    return 0 if ok else 2


def cmd_doctor(args: argparse.Namespace) -> int:
    config = load_config(args.project_root, args.framework_dir)
    return _run_doctor(config, args.godot)


def cmd_init(args: argparse.Namespace) -> int:
    root = find_project_root(args.project_root)
    _write_config(root, force=args.force)
    if args.ci:
        workflow = root / ".github" / "workflows" / "gdextest.yml"
        if workflow.exists() and not args.force:
            print(f"gdextest: keeping existing {workflow}")
        else:
            workflow.parent.mkdir(parents=True, exist_ok=True)
            workflow.write_text(CI_TEMPLATE, encoding="utf-8")
            print(f"gdextest: wrote {workflow}")
    return 0


def cmd_scaffold(args: argparse.Namespace) -> int:
    """Wire the SConstruct, generate an entry + smoke suite, then run doctor.

    Without `--apply` this prints what it would do and returns 2. With `--apply`
    the SConstruct is patched (backup written first) and verified with a syntax
    check; existing entry/suite files are preserved unless `--force` is given.
    """
    root = find_project_root(args.project_root)
    config = load_config(root, args.framework_dir)
    sconstruct = root / "SConstruct"
    if not sconstruct.is_file():
        print(f"gdextest: error: no SConstruct found at {sconstruct}; "
              "scaffold needs the consumer SConstruct", file=sys.stderr)
        return 2
    if _sconstruct_wired(root):
        print("gdextest: SConstruct already references the gdextest SConscript")
    elif args.apply:
        original = sconstruct.read_text(encoding="utf-8")
        backup = root / "SConstruct.gdextest.bak"
        backup.write_text(original, encoding="utf-8")
        patched = original.rstrip() + "\n" + SCONSTRUCT_SNIPPET
        sconstruct.write_text(patched, encoding="utf-8")
        try:
            compile(patched, str(sconstruct), "exec")
        except SyntaxError as error:
            sconstruct.write_text(original, encoding="utf-8")
            print(f"gdextest: error: SConstruct patch failed its syntax check; "
                  f"restored the original ({backup} kept): {error}", file=sys.stderr)
            return 2
        print(f"gdextest: wired {sconstruct} (backup: {backup})")
    else:
        print("gdextest: SConstruct does not call extern/gdextest/SConscript")
        print("gdextest: re-run with --apply to patch it (a .bak backup is written first)")
        return 2

    # testsupport/ lives outside the default tests/**/*.cpp suite glob so the
    # generated entry is compiled exactly once (as the entry, not as a suite).
    entry_path = root / "testsupport" / "entry.cpp"
    if entry_path.exists() and not args.force:
        print(f"gdextest: keeping existing {entry_path}")
    else:
        entry_path.parent.mkdir(parents=True, exist_ok=True)
        entry_path.write_text(
            ENTRY_TEMPLATE.replace("@PLUGIN_CLASS@", config.plugin_class)
                         .replace("@ENTRY_SYMBOL@", config.entry_symbol),
            encoding="utf-8")
        print(f"gdextest: wrote {entry_path}")

    smoke_path = root / "tests" / "smoke.cpp"
    if smoke_path.exists() and not args.force:
        print(f"gdextest: keeping existing {smoke_path}")
    else:
        (root / "tests").mkdir(parents=True, exist_ok=True)
        smoke_path.write_text(SMOKE_SUITE, encoding="utf-8")
        print(f"gdextest: wrote {smoke_path}")

    return _run_doctor(config, args.godot)


def _extract_junit_passthrough(user_args: list[str]) -> str | None:
    """Pull a --gdextest-junit=<path> pass-through arg out of the user list.

    The runner only speaks JSON; the CLI converts that JSON to JUnit after the
    run, so the runner never sees this flag.
    """
    for arg in list(user_args):
        if arg.startswith("--gdextest-junit="):
            user_args.remove(arg)
            return arg[len("--gdextest-junit="):]
    return None


def cmd_report(args: argparse.Namespace) -> int:
    """Merge shard result documents into one JSON/JUnit report.

    Parallel CI runs `test --gdextest-shard=k/n --json=shard{k}.json` per job;
    `report shard*.json --json=merged.json` turns them into a single document.
    Exits 1 when any merged test failed or crashed (mirrors the runner).
    """
    documents = _load_result_documents(args.paths)
    merged = _merge_documents(documents)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as handle:
            json.dump(merged, handle, indent=2)
        print(f"gdextest: wrote {args.json}")
    else:
        print(json.dumps(merged, indent=2))
    if args.junit:
        _write_junit(merged["results"], args.junit)
        print(f"gdextest: wrote {args.junit}")
    return 1 if merged["totals"]["fail"] or merged["totals"]["crashed"] else 0


def cmd_list(args: argparse.Namespace) -> int:
    config = load_config(args.project_root, args.framework_dir)
    _run_build(config)
    executable = godot_executable(config, args.godot)
    _warm_fixture(config, executable)
    user_args = [*getattr(args, "passthrough", []), "--gdextest-list"]
    command = _godot_command(config, executable, *user_args)
    return subprocess.run(command, cwd=config.project_root, env=_run_environment(config)).returncode


def cmd_test(args: argparse.Namespace) -> int:
    root = find_project_root(args.project_root)
    config_path = root / ".gdextest.toml"
    if not config_path.exists():
        _write_config(root)
    config = load_config(root, args.framework_dir)
    doctor_result = _run_doctor(config, args.godot, allow_injection=True)
    if doctor_result:
        return doctor_result
    _run_build(config)
    executable = godot_executable(config, args.godot)
    expected = ".".join(config.godot_version.split(".")[:2])
    actual = godot_version(executable)
    if expected and not actual.startswith(expected):
        raise RuntimeError(f"Godot {actual} found, but gdextest requires {config.godot_version}")
    # Unknown --gdextest-* flags pass through verbatim; the runner's exit code 2
    # still guards typos. CLI-generated flags are appended after, so they win.
    user_args: list[str] = list(getattr(args, "passthrough", []))
    if args.filter:
        user_args.append(f"--gdextest-filter={args.filter}")
    if args.shard:
        user_args.append(f"--gdextest-shard={args.shard}")
    if args.shuffle is not None:
        user_args.append("--gdextest-shuffle" if args.shuffle == "" else
                         f"--gdextest-shuffle={args.shuffle}")
    # Runtime budgets from [gdextest.test]; always forwarded so the runner honors
    # TOML values without a framework rebuild.
    user_args.append(f"--gdextest-timeout-ms={config.timeout_ms}")
    user_args.append(f"--gdextest-isolate-timeout-sec={config.isolate_timeout_sec}")
    user_args.append(f"--gdextest-flaky-retries={config.flaky_retries}")

    junit_path = getattr(args, "junit", None)
    passthrough_junit = _extract_junit_passthrough(user_args)
    if passthrough_junit and not junit_path:
        junit_path = passthrough_junit
    json_path = None
    if args.json:
        # Godot chdirs to the fixture dir (--path), so a relative path would resolve
        # against the fixture, not the user's cwd. Resolve it up front.
        json_path = os.path.abspath(args.json)
        user_args.append(f"--gdextest-json={json_path}")
    elif junit_path:
        # JUnit is derived from the runner's JSON document; keep it in a temp file.
        json_path = os.path.join(tempfile.gettempdir(), f"gdextest-results-{os.getpid()}.json")
        user_args.append(f"--gdextest-json={json_path}")
    _warm_fixture(config, executable)
    code = subprocess.run(_godot_command(config, executable, *user_args),
                          cwd=config.project_root, env=_run_environment(config)).returncode
    if junit_path and json_path and os.path.isfile(json_path):
        try:
            _json_to_junit(json_path, os.path.abspath(junit_path))
            print(f"gdextest: wrote {os.path.abspath(junit_path)}")
        except (OSError, ValueError) as error:
            print(f"gdextest: warning: could not write JUnit output: {error}", file=sys.stderr)
    if json_path and not args.json:
        try:
            os.unlink(json_path)
        except OSError:
            pass
    return code


def cmd_clean(args: argparse.Namespace) -> int:
    config = load_config(args.project_root, args.framework_dir)
    for relative in (config.fixture_dir, config.build_dir):
        path = config.project_root / relative
        if path.exists():
            shutil.rmtree(path)
            print(f"gdextest: removed {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gdextest")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--framework-dir")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init", help="create starter configuration")
    init.add_argument("--ci", action="store_true", help="also create a GitHub Actions workflow")
    init.add_argument("--force", action="store_true")
    init.set_defaults(function=cmd_init)

    doctor = subparsers.add_parser("doctor", help="validate the consumer environment")
    doctor.add_argument("--godot")
    doctor.set_defaults(function=cmd_doctor)

    scaffold = subparsers.add_parser(
        "scaffold", help="wire SConstruct and generate entry + smoke suite")
    scaffold.add_argument("--godot")
    scaffold.add_argument("--apply", action="store_true",
                          help="patch SConstruct (backup first) instead of printing")
    scaffold.add_argument("--force", action="store_true",
                          help="overwrite existing generated files")
    scaffold.set_defaults(function=cmd_scaffold)

    test = subparsers.add_parser("test", help="build and run tests")
    test.add_argument("--godot")
    test.add_argument("--filter")
    test.add_argument("--shard")
    test.add_argument("--shuffle", nargs="?", const="", default=None)
    test.add_argument("--json")
    test.add_argument("--junit", help="also write JUnit XML (converted from the run's JSON)")
    test.set_defaults(function=cmd_test)

    report = subparsers.add_parser("report", help="merge shard result JSON into one report")
    report.add_argument("paths", nargs="+", help="result JSON files or globs, e.g. 'shard*.json'")
    report.add_argument("--json", help="write merged JSON here (default: stdout)")
    report.add_argument("--junit", help="write merged results as JUnit XML here")
    report.set_defaults(function=cmd_report)

    listing = subparsers.add_parser("list", help="build and list tests")
    listing.add_argument("--godot")
    listing.set_defaults(function=cmd_list)

    clean = subparsers.add_parser("clean", help="remove generated test output")
    clean.set_defaults(function=cmd_clean)

    args, extras = parser.parse_known_args(argv)
    # Runner flags (--gdextest-*) are not CLI options; pass them through so the
    # CLI is never the bottleneck when the runner grows flags. Anything else
    # unknown is a real usage error.
    args.passthrough = [arg for arg in extras if arg.startswith("--gdextest-")]
    unrecognized = [arg for arg in extras if not arg.startswith("--gdextest-")]
    if unrecognized:
        print(f"gdextest: error: unrecognized arguments: {' '.join(unrecognized)}",
              file=sys.stderr)
        return 2
    try:
        return args.function(args)
    except (FileNotFoundError, RuntimeError, OSError, subprocess.CalledProcessError) as error:
        print(f"gdextest: error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
