#!/usr/bin/env python3
"""Command-line integration for gdextest consumers."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys

from gdextest_config import (
    Config,
    discover_sources,
    find_project_root,
    godot_executable,
    godot_version,
    load_config,
    locate_extension_library,
    locate_extension_manifest,
)


CONFIG_TEMPLATE = '''[gdextest]
version = "1"
godot_version = "4.5"

[gdextest.tests]
sources = ["tests/**/*.cpp"]

[gdextest.host]
mode = "editor"
entry_symbol = "gdextest_library_init"
plugin_class = "GdextestPlugin"

[gdextest.fixture]
directory = "build/gdextest/project"
project_name = "gdextest fixture"
native_extensions = []
assets = []

[gdextest.output]
directory = "bin"
name = "libgdextest"

[gdextest.build]
args = []
'''

CI_TEMPLATE = '''name: gdextest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install SCons
        run: python3 -m pip install scons
      - name: Download Godot 4.5
        run: |
          curl -fsSL -o godot.zip https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          unzip -o godot.zip
          chmod +x Godot_v4.5-stable_linux.x86_64
      - name: Run gdextest
        run: python3 extern/gdextest/tools/gdextest.py test --godot "$GITHUB_WORKSPACE/Godot_v4.5-stable_linux.x86_64"
'''

# Scaffolded GDExtension entry (mirrors src/gdextest_entry.cpp). The plugin
# class name and entry symbol come from .gdextest.toml so the generated fixture
# wrapper instantiates exactly the class the entry registers. @PLUGIN_CLASS@ and
# @ENTRY_SYMBOL@ are replaced with str.replace so template braces stay literal.
ENTRY_TEMPLATE = '''// GDExtension entry + EditorPlugin shell generated by `gdextest scaffold`.
// The plugin class and entry symbol are sourced from .gdextest.toml
// ([gdextest.host] plugin_class / entry_symbol). Test build only.
#ifdef GDEXTEST_ENABLED

#include <godot_cpp/classes/editor_plugin.hpp>
#include <godot_cpp/godot.hpp>

namespace gdextest_adapter { void maybe_run(godot::Node *tree_node); }

class @PLUGIN_CLASS@ : public godot::EditorPlugin {
    GDCLASS(@PLUGIN_CLASS@, godot::EditorPlugin)

protected:
    static void _bind_methods() {
        godot::ClassDB::bind_method(godot::D_METHOD("_run_tests"),
                                    &@PLUGIN_CLASS@::_run_tests);
    }

public:
    void _ready() override {
        call_deferred("_run_tests");
    }

    void _run_tests() {
        gdextest_adapter::maybe_run(this);
    }
};

using namespace godot;

void initialize_test_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_EDITOR) return;
    ClassDB::register_class<@PLUGIN_CLASS@>();
}

void uninitialize_test_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_EDITOR) return;
}

extern "C" {

GDExtensionBool GDE_EXPORT @ENTRY_SYMBOL@(
        GDExtensionInterfaceGetProcAddress p_get_proc_address,
        const GDExtensionClassLibraryPtr p_library,
        GDExtensionInitialization *r_initialization) {
    godot::GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library,
                                                   r_initialization);
    init_obj.register_initializer(&initialize_test_module);
    init_obj.register_terminator(&uninitialize_test_module);
    init_obj.set_minimum_library_initialization_level(
            godot::MODULE_INITIALIZATION_LEVEL_EDITOR);
    return init_obj.init();
}

}  // extern "C"

#endif // GDEXTEST_ENABLED
'''

SMOKE_SUITE = '''// Smoke suite generated by `gdextest scaffold`.
#include "framework/assert.h"
#include "framework/registry.h"

GDEX_TEST(smoke, framework_is_wired) {
    GDEX_EXPECT(true);
}
'''

SCONSTRUCT_SNIPPET = '''
# --- gdextest test framework (scaffolded; see consumer-guide §5) ---
lib = env.SConscript(
    "extern/gdextest/SConscript",
    variant_dir="build/gdextest", duplicate=0,
    exports={"env": env, "gdextest": {
        "entry": "testsupport/entry.cpp",
    }},
)
if lib:
    Default(lib)
'''


def _framework_path(config: Config) -> str:
    return str(config.framework_dir)


def _scons_command(config: Config) -> list[str]:
    return ["scons", "tests=true", *config.build_args]


def _library_path(config: Config) -> Path | None:
    """Locate the built test library, or None if the SConscript did not run."""
    output = config.project_root / config.out_dir
    if not output.is_dir():
        return None
    candidates = sorted(output.glob(config.out_name + "*"))
    return candidates[0] if candidates else None


def _run_build(config: Config) -> None:
    sources = discover_sources(config)
    if not sources:
        raise RuntimeError("no test sources found; check [gdextest.tests].sources")
    errors = config.validate()
    if errors:
        raise RuntimeError("configuration is invalid:\n  " + "\n  ".join(errors))
    env = os.environ.copy()
    env["gdextest_PROJECT_ROOT"] = str(config.project_root)
    env["gdextest_FRAMEWORK_DIR"] = _framework_path(config)
    env["gdextest_SOURCES"] = os.pathsep.join(
        str(path.relative_to(config.project_root)) for path in sources)
    env["gdextest_HOST_MODE"] = config.host_mode
    if config.bootstrap:
        env["gdextest_BOOTSTRAP"] = config.bootstrap
    subprocess.run(_scons_command(config), cwd=config.project_root, env=env, check=True)
    if not _library_path(config):
        raise RuntimeError(
            "the test library was not produced; your SConstruct does not appear to "
            "call extern/gdextest/SConscript — see consumer-guide §5")


def _godot_command(config: Config, executable: str, *user_args: str) -> list[str]:
    mode_args = ["--headless", "--editor"] if config.host_mode == "editor" else ["--headless"]
    return [executable, *mode_args, "--path", str(config.fixture_path), "--",
            "--gdextest-run", *user_args]


def _run_environment(config: Config) -> dict[str, str]:
    environment = os.environ.copy()
    user_data = config.project_root / config.build_dir / "user-data"
    # user:// must be hermetic across runs: residue from a previous run (session
    # files, temp repos) would leak into "should not exist at start" assertions.
    if user_data.exists():
        shutil.rmtree(user_data)
    user_data.mkdir(parents=True)
    environment["XDG_DATA_HOME"] = str(user_data)
    return environment


def _print_check(label: str, value: str, ok: bool) -> bool:
    print(f"{'[ok]' if ok else '[!!]'} {label}: {value}", flush=True)
    return ok


def _write_config(root: Path, *, force: bool = False) -> bool:
    """Create the starter config without replacing consumer changes by default."""
    config_path = root / ".gdextest.toml"
    if config_path.exists() and not force:
        print(f"gdextest: keeping existing {config_path}")
        return False
    config_path.write_text(CONFIG_TEMPLATE, encoding="utf-8")
    print(f"gdextest: wrote {config_path}")
    return True


def _sconstruct_wired(root: Path) -> bool:
    sconstruct = root / "SConstruct"
    if not sconstruct.is_file():
        return False
    content = sconstruct.read_text(encoding="utf-8", errors="replace")
    return "gdextest" in content


def _run_doctor(config: Config, godot_override: str | None) -> int:
    """Run the environment checks shared by `doctor` and every test run."""
    print("gdextest doctor", flush=True)
    print(f"project root: {config.project_root}", flush=True)
    print(f"framework:    {config.framework_dir}", flush=True)
    print(f"host mode:    {config.host_mode}", flush=True)
    source_count = len(discover_sources(config))
    print(f"test sources: {source_count}", flush=True)

    ok = True
    errors = config.validate()
    if not errors and not source_count:
        errors.append("no test sources found; check [gdextest.tests].sources")
    ok &= _print_check("configuration", "valid" if not errors else "; ".join(errors), not errors)
    try:
        executable = godot_executable(config, godot_override)
        version = godot_version(executable)
        expected = ".".join(config.godot_version.split(".")[:2])
        ok &= _print_check("Godot", f"{executable} ({version})", version.startswith(expected))
    except (FileNotFoundError, OSError) as error:
        ok &= _print_check("Godot", str(error), False)
    scons = shutil.which("scons")
    ok &= _print_check("SCons", scons or "not found", scons is not None)
    framework_sconscript = config.framework_dir / "SConscript"
    ok &= _print_check("framework SConscript", str(framework_sconscript),
                       framework_sconscript.is_file())
    sconstruct = config.project_root / "SConstruct"
    if sconstruct.is_file():
        content = sconstruct.read_text(encoding="utf-8", errors="replace")
        if "gdextest" in content:
            ok &= _print_check("SConstruct wiring", "gdextest SConscript referenced", True)
        elif "SConscript" not in content:
            ok &= _print_check(
                "SConstruct wiring",
                "no gdextest/SConscript reference; SConstruct must call "
                "extern/gdextest/SConscript (consumer-guide §5)", False)
        else:
            print("[..] SConstruct wiring: SConscript used but no gdextest reference; "
                  "verify extern/gdextest/SConscript is called somewhere", flush=True)
    else:
        ok &= _print_check("SConstruct wiring", "SConstruct not found", False)
    extension_library = locate_extension_library(config)
    extension_manifest = locate_extension_manifest(config)
    if extension_library or extension_manifest:
        ok &= _print_check("consumer extension library", str(extension_library),
                           bool(extension_library and extension_library.is_file()))
        ok &= _print_check("consumer extension manifest", str(extension_manifest),
                           bool(extension_manifest and extension_manifest.is_file()))
    return 0 if ok else 2


def cmd_doctor(args: argparse.Namespace) -> int:
    config = load_config(args.project_root, args.framework_dir)
    return _run_doctor(config, args.godot)


def cmd_init(args: argparse.Namespace) -> int:
    root = find_project_root(args.project_root)
    _write_config(root, force=args.force)
    if args.ci:
        workflow = root / ".github" / "workflows" / "gdextest.yml"
        if workflow.exists() and not args.force:
            print(f"gdextest: keeping existing {workflow}")
        else:
            workflow.parent.mkdir(parents=True, exist_ok=True)
            workflow.write_text(CI_TEMPLATE, encoding="utf-8")
            print(f"gdextest: wrote {workflow}")
    return 0


def cmd_scaffold(args: argparse.Namespace) -> int:
    """Wire the SConstruct, generate an entry + smoke suite, then run doctor.

    Without `--apply` this prints what it would do and returns 2. With `--apply`
    the SConstruct is patched (backup written first) and verified with a syntax
    check; existing entry/suite files are preserved unless `--force` is given.
    """
    root = find_project_root(args.project_root)
    config = load_config(root, args.framework_dir)
    sconstruct = root / "SConstruct"
    if not sconstruct.is_file():
        print(f"gdextest: error: no SConstruct found at {sconstruct}; "
              "scaffold needs the consumer SConstruct", file=sys.stderr)
        return 2
    if _sconstruct_wired(root):
        print("gdextest: SConstruct already references the gdextest SConscript")
    elif args.apply:
        original = sconstruct.read_text(encoding="utf-8")
        backup = root / "SConstruct.gdextest.bak"
        backup.write_text(original, encoding="utf-8")
        patched = original.rstrip() + "\n" + SCONSTRUCT_SNIPPET
        sconstruct.write_text(patched, encoding="utf-8")
        try:
            compile(patched, str(sconstruct), "exec")
        except SyntaxError as error:
            sconstruct.write_text(original, encoding="utf-8")
            print(f"gdextest: error: SConstruct patch failed its syntax check; "
                  f"restored the original ({backup} kept): {error}", file=sys.stderr)
            return 2
        print(f"gdextest: wired {sconstruct} (backup: {backup})")
    else:
        print("gdextest: SConstruct does not call extern/gdextest/SConscript")
        print("gdextest: re-run with --apply to patch it (a .bak backup is written first)")
        return 2

    # testsupport/ lives outside the default tests/**/*.cpp suite glob so the
    # generated entry is compiled exactly once (as the entry, not as a suite).
    entry_path = root / "testsupport" / "entry.cpp"
    if entry_path.exists() and not args.force:
        print(f"gdextest: keeping existing {entry_path}")
    else:
        entry_path.parent.mkdir(parents=True, exist_ok=True)
        entry_path.write_text(
            ENTRY_TEMPLATE.replace("@PLUGIN_CLASS@", config.plugin_class)
                         .replace("@ENTRY_SYMBOL@", config.entry_symbol),
            encoding="utf-8")
        print(f"gdextest: wrote {entry_path}")

    smoke_path = root / "tests" / "smoke.cpp"
    if smoke_path.exists() and not args.force:
        print(f"gdextest: keeping existing {smoke_path}")
    else:
        (root / "tests").mkdir(parents=True, exist_ok=True)
        smoke_path.write_text(SMOKE_SUITE, encoding="utf-8")
        print(f"gdextest: wrote {smoke_path}")

    return _run_doctor(config, args.godot)


def cmd_list(args: argparse.Namespace) -> int:
    config = load_config(args.project_root, args.framework_dir)
    _run_build(config)
    executable = godot_executable(config, args.godot)
    user_args = [*getattr(args, "passthrough", []), "--gdextest-list"]
    command = _godot_command(config, executable, *user_args)
    return subprocess.run(command, cwd=config.project_root, env=_run_environment(config)).returncode


def cmd_test(args: argparse.Namespace) -> int:
    root = find_project_root(args.project_root)
    config_path = root / ".gdextest.toml"
    if not config_path.exists():
        _write_config(root)
    config = load_config(root, args.framework_dir)
    doctor_result = _run_doctor(config, args.godot)
    if doctor_result:
        return doctor_result
    _run_build(config)
    executable = godot_executable(config, args.godot)
    expected = ".".join(config.godot_version.split(".")[:2])
    actual = godot_version(executable)
    if expected and not actual.startswith(expected):
        raise RuntimeError(f"Godot {actual} found, but gdextest requires {config.godot_version}")
    # Unknown --gdextest-* flags pass through verbatim; the runner's exit code 2
    # still guards typos. CLI-generated flags are appended after, so they win.
    user_args: list[str] = list(getattr(args, "passthrough", []))
    if args.filter:
        user_args.append(f"--gdextest-filter={args.filter}")
    if args.shard:
        user_args.append(f"--gdextest-shard={args.shard}")
    if args.shuffle is not None:
        user_args.append("--gdextest-shuffle" if args.shuffle == "" else
                         f"--gdextest-shuffle={args.shuffle}")
    if args.json:
        # Godot chdirs to the fixture dir (--path), so a relative path would resolve
        # against the fixture, not the user's cwd. Resolve it up front.
        user_args.append(f"--gdextest-json={os.path.abspath(args.json)}")
    return subprocess.run(_godot_command(config, executable, *user_args),
                          cwd=config.project_root, env=_run_environment(config)).returncode


def cmd_clean(args: argparse.Namespace) -> int:
    config = load_config(args.project_root, args.framework_dir)
    for relative in (config.fixture_dir, config.build_dir):
        path = config.project_root / relative
        if path.exists():
            shutil.rmtree(path)
            print(f"gdextest: removed {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gdextest")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--framework-dir")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init = subparsers.add_parser("init", help="create starter configuration")
    init.add_argument("--ci", action="store_true", help="also create a GitHub Actions workflow")
    init.add_argument("--force", action="store_true")
    init.set_defaults(function=cmd_init)

    doctor = subparsers.add_parser("doctor", help="validate the consumer environment")
    doctor.add_argument("--godot")
    doctor.set_defaults(function=cmd_doctor)

    scaffold = subparsers.add_parser(
        "scaffold", help="wire SConstruct and generate entry + smoke suite")
    scaffold.add_argument("--godot")
    scaffold.add_argument("--apply", action="store_true",
                          help="patch SConstruct (backup first) instead of printing")
    scaffold.add_argument("--force", action="store_true",
                          help="overwrite existing generated files")
    scaffold.set_defaults(function=cmd_scaffold)

    test = subparsers.add_parser("test", help="build and run tests")
    test.add_argument("--godot")
    test.add_argument("--filter")
    test.add_argument("--shard")
    test.add_argument("--shuffle", nargs="?", const="", default=None)
    test.add_argument("--json")
    test.set_defaults(function=cmd_test)

    listing = subparsers.add_parser("list", help="build and list tests")
    listing.add_argument("--godot")
    listing.set_defaults(function=cmd_list)

    clean = subparsers.add_parser("clean", help="remove generated test output")
    clean.set_defaults(function=cmd_clean)

    args, extras = parser.parse_known_args(argv)
    # Runner flags (--gdextest-*) are not CLI options; pass them through so the
    # CLI is never the bottleneck when the runner grows flags. Anything else
    # unknown is a real usage error.
    args.passthrough = [arg for arg in extras if arg.startswith("--gdextest-")]
    unrecognized = [arg for arg in extras if not arg.startswith("--gdextest-")]
    if unrecognized:
        print(f"gdextest: error: unrecognized arguments: {' '.join(unrecognized)}",
              file=sys.stderr)
        return 2
    try:
        return args.function(args)
    except (FileNotFoundError, RuntimeError, OSError, subprocess.CalledProcessError) as error:
        print(f"gdextest: error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
