#!/usr/bin/env python3
"""Generate the minimal Godot project used to load and run a gdextest library.

The generated project is disposable build output. It contains the native test
extension, a valid manifest, and the scan-safe editor plugin wrapper. Keeping
this in the framework removes the need for consumers to copy a fixture template.
"""

from __future__ import annotations

import argparse
import configparser
import os
import re
import shutil
from pathlib import Path
from typing import Iterable
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gdextest_config import copy_globbed_assets


PLUGIN_CFG = '''[plugin]

name="gdextest"
description="Runs gdextest suites inside the editor and quits with pass/fail."
author="gdextest"
version="1.0"
script="plugin.gd"
'''

EDITOR_PLUGIN_GD = '''@tool
extends EditorPlugin

# EditorPlugin._ready() runs while the editor is still starting its first scan.
# Wait until the scan is complete before creating the native host: quitting while
# the scan thread is starting can crash Godot during shutdown.
const SCAN_TIMEOUT_MS := 20000
var test_plugin: Node
var _start_ms := 0

func _ready() -> void:
    _start_ms = Time.get_ticks_msec()
    get_tree().process_frame.connect(_on_frame)

func _on_frame() -> void:
    var fs := EditorInterface.get_resource_filesystem()
    if fs.is_scanning():
        if Time.get_ticks_msec() - _start_ms >= SCAN_TIMEOUT_MS:
            push_error("gdextest: editor filesystem scan did not finish before timeout")
            get_tree().quit(2)
        return
    get_tree().process_frame.disconnect(_on_frame)
    test_plugin = GdextestPlugin.new()
    add_child(test_plugin)

func _exit_tree() -> void:
    if get_tree() and get_tree().process_frame.is_connected(_on_frame):
        get_tree().process_frame.disconnect(_on_frame)
    # The native plugin owns the test run and requests process shutdown. Do not
    # remove it during editor teardown; Godot owns plugin lifetime here.
'''

RUNTIME_PLUGIN_GD = '''extends Node

# Runtime projects do not have EditorPlugin or filesystem-scan lifecycle hooks.
# The native test plugin is instantiated on the first process frame so the
# extension has completed initialization before the runner is called.
var test_plugin: Node

func _ready() -> void:
    get_tree().process_frame.connect(_on_frame, CONNECT_ONE_SHOT)

func _on_frame() -> void:
    test_plugin = GdextestPlugin.new()
    add_child(test_plugin)

func _exit_tree() -> void:
    # The native plugin owns the test run and requests process shutdown. Do not
    # remove it during editor teardown; Godot owns plugin lifetime here.
'''


def _godot_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _packed_strings(values: Iterable[str]) -> str:
    return "PackedStringArray(" + ", ".join(_godot_quote(v) for v in values) + ")"


def _manifest(entry_symbol: str, godot_version: str, library_key: str,
              library_basename: str) -> str:
    return f'''[configuration]

entry_symbol = {_godot_quote(entry_symbol)}
compatibility_minimum = {_godot_quote(godot_version)}

[libraries]

{library_key} = {_godot_quote("res://addons/gdextest/bin/" + library_basename)}
'''


def _project(project_name: str, godot_version: str,
             manifest_basename: str,
             native_extensions: Iterable[str],
             host_mode: str,
             extension_manifest: str | None = None) -> str:
    paths = [f"res://addons/gdextest/{manifest_basename}"]
    if extension_manifest:
        paths.append("res://addons/consumer/" + Path(extension_manifest).name)
    paths.extend(native_extensions)
    autoload = '' if host_mode == "editor" else '\n[autoload]\n\ngdextestHost="*res://addons/gdextest/runtime.gd"\n'
    plugins = ('\n[editor_plugins]\n\nenabled=' +
               _packed_strings(["res://addons/gdextest/plugin.cfg"]) + '\n'
               if host_mode == "editor" else '')
    return f'''; Generated by gdextest. Do not edit; this directory is disposable build output.

config_version=5

[application]

config/name={_godot_quote(project_name)}
config/features={_packed_strings([godot_version])}

[native_extensions]

paths={_packed_strings(paths)}

{plugins}{autoload}'''


def _stage_consumer_manifest(manifest: Path, destination: Path,
                             library_basename: str | None) -> None:
    """Copy a consumer's .gdextension into the fixture, pointing every
    [libraries] entry at the fixture's addons/consumer/bin copy of the library.

    The consumer's manifest references its own addon layout
    (res://addons/<name>/bin/...) which does not exist inside the generated
    fixture; Godot resolves library paths at load time, so they are rewritten
    to the staged copy. The [configuration]/[dependencies] sections are kept
    verbatim. An unparseable manifest is copied as-is and Godot will surface
    the error.
    """
    if library_basename is None:
        shutil.copy2(manifest, destination)
        return
    parser = configparser.ConfigParser()
    try:
        with manifest.open(encoding="utf-8") as handle:
            parser.read_file(handle)
    except (OSError, configparser.Error):
        shutil.copy2(manifest, destination)
        return
    if parser.has_section("libraries"):
        for key in parser["libraries"]:
            parser["libraries"][key] = f'res://addons/consumer/bin/{library_basename}'
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        parser.write(handle)


def generate_fixture(*, project_root: str | os.PathLike[str], library_path: str | os.PathLike[str],
                     library_basename: str, manifest_basename: str,
                     entry_symbol: str = "gdextest_library_init",
                     plugin_class: str = "GdextestPlugin",
                     project_name: str = "gdextest fixture",
                     godot_version: str = "4.5",
                     library_key: str = "linux.debug.x86_64",
                     native_extensions: Iterable[str] = (),
                     extension_library: str | os.PathLike[str] | None = None,
                     extension_manifest: str | os.PathLike[str] | None = None,
                     fixture_assets: Iterable[str] = (),
                     host_mode: str = "editor",
                     project_source_root: str | os.PathLike[str] | None = None,
                     scan_timeout_ms: int = 20000) -> None:
    """Create or refresh a generated fixture directory.

    `plugin_class` names the native EditorPlugin registered by the entry point;
    the generated host wrapper instantiates it after the editor scan settles.
    `scan_timeout_ms` bounds how long the editor's first filesystem scan may
    take before the host fails the run (slow CI machines, large repos).
    """
    if host_mode not in {"editor", "runtime"}:
        raise ValueError(f"unsupported gdextest host mode: {host_mode}")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", plugin_class):
        raise ValueError(f"invalid plugin_class: {plugin_class!r}")
    if scan_timeout_ms <= 0:
        raise ValueError(f"invalid scan_timeout_ms: {scan_timeout_ms!r}")
    root = Path(project_root)
    library = Path(library_path)
    addon = root / "addons" / "gdextest"
    binary_dir = addon / "bin"
    binary_dir.mkdir(parents=True, exist_ok=True)

    # Generated output may be reused with a different host mode.
    for stale in (addon / "plugin.cfg", addon / "plugin.gd", addon / "runtime.gd"):
        if stale.exists():
            stale.unlink()
    # Generated output may also be reused with a different config (e.g. a
    # previous out_name). Godot's editor scans every .gdextension it finds in
    # the project and tries to load it, so a stale manifest + library from an
    # earlier run would error (and can crash the editor) — remove everything
    # except the manifest/library being written now.
    for stale in addon.glob("*.gdextension"):
        if stale.name != manifest_basename:
            stale.unlink()
    for stale in binary_dir.iterdir():
        if stale.is_file():
            stale.unlink()

    (root / "project.godot").write_text(
        _project(project_name, godot_version, manifest_basename, native_extensions, host_mode,
                 Path(extension_manifest).name if extension_manifest else None),
        encoding="utf-8")
    if host_mode == "editor":
        (addon / "plugin.cfg").write_text(PLUGIN_CFG, encoding="utf-8")
        (addon / "plugin.gd").write_text(
            EDITOR_PLUGIN_GD.replace("GdextestPlugin", plugin_class)
                            .replace("const SCAN_TIMEOUT_MS := 20000",
                                     f"const SCAN_TIMEOUT_MS := {scan_timeout_ms}"),
            encoding="utf-8")
    else:
        (addon / "runtime.gd").write_text(
            RUNTIME_PLUGIN_GD.replace("GdextestPlugin", plugin_class), encoding="utf-8")
    (addon / manifest_basename).write_text(
        _manifest(entry_symbol, godot_version, library_key, library_basename),
        encoding="utf-8")

    destination = binary_dir / library_basename
    if not library.is_file():
        raise FileNotFoundError(f"gdextest library does not exist: {library}")
    shutil.copy2(library, destination)

    if extension_library:
        extension = Path(extension_library)
        extension_destination = root / "addons" / "consumer" / "bin" / extension.name
        extension_destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(extension, extension_destination)
    if extension_manifest:
        manifest = Path(extension_manifest)
        _stage_consumer_manifest(
            manifest,
            root / "addons" / "consumer" / manifest.name,
            extension.name if extension_library else None,
        )
    if project_source_root:
        copy_globbed_assets(Path(project_source_root), root, fixture_assets)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--library", required=True, type=Path)
    parser.add_argument("--library-basename")
    parser.add_argument("--manifest-basename", default="gdextest.gdextension")
    parser.add_argument("--entry-symbol", default="gdextest_library_init")
    parser.add_argument("--plugin-class", default="GdextestPlugin")
    parser.add_argument("--project-name", default="gdextest fixture")
    parser.add_argument("--godot-version", default="4.5")
    parser.add_argument("--library-key", default="linux.debug.x86_64")
    parser.add_argument("--native-extension", action="append", default=[])
    parser.add_argument("--fixture-asset", action="append", default=[])
    parser.add_argument("--host-mode", choices=("editor", "runtime"), default="editor")
    parser.add_argument("--scan-timeout-ms", type=int, default=20000)
    args = parser.parse_args()
    basename = args.library_basename or args.library.name
    generate_fixture(
        project_root=args.project_root,
        library_path=args.library,
        library_basename=basename,
        manifest_basename=args.manifest_basename,
        entry_symbol=args.entry_symbol,
        plugin_class=args.plugin_class,
        project_name=args.project_name,
        godot_version=args.godot_version,
        library_key=args.library_key,
        native_extensions=args.native_extension,
        fixture_assets=args.fixture_asset,
        host_mode=args.host_mode,
        project_source_root=Path.cwd(),
        scan_timeout_ms=args.scan_timeout_ms,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
