#!/usr/bin/env python3
"""Generate the minimal Godot project used to load and run a gdextest library.

The generated project is disposable build output. It contains the native test
extension, a valid manifest, and the scan-safe editor plugin wrapper. Keeping
this in the framework removes the need for consumers to copy a fixture template.
"""

from __future__ import annotations

import argparse
import os
import shutil
from pathlib import Path
from typing import Iterable
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gdextest_config import copy_globbed_assets


PLUGIN_CFG = '''[plugin]

name="gdextest"
description="Runs gdextest suites inside the editor and quits with pass/fail."
author="gdextest"
version="1.0"
script="plugin.gd"
'''

EDITOR_PLUGIN_GD = '''@tool
extends EditorPlugin

# EditorPlugin._ready() runs while the editor is still starting its first scan.
# Wait until the scan is complete before creating the native host: quitting while
# the scan thread is starting can crash Godot during shutdown.
const SCAN_TIMEOUT_MS := 20000
var test_plugin: Node
var _start_ms := 0

func _ready() -> void:
    _start_ms = Time.get_ticks_msec()
    get_tree().process_frame.connect(_on_frame)

func _on_frame() -> void:
    var fs := EditorInterface.get_resource_filesystem()
    if fs.is_scanning():
        if Time.get_ticks_msec() - _start_ms >= SCAN_TIMEOUT_MS:
            push_error("gdextest: editor filesystem scan did not finish before timeout")
            get_tree().quit(2)
        return
    get_tree().process_frame.disconnect(_on_frame)
    test_plugin = GdextestPlugin.new()
    add_child(test_plugin)

func _exit_tree() -> void:
    if get_tree() and get_tree().process_frame.is_connected(_on_frame):
        get_tree().process_frame.disconnect(_on_frame)
    if test_plugin:
        remove_child(test_plugin)
        test_plugin.queue_free()
        test_plugin = null
'''

RUNTIME_PLUGIN_GD = '''extends Node

# Runtime projects do not have EditorPlugin or filesystem-scan lifecycle hooks.
# The native test plugin is instantiated on the first process frame so the
# extension has completed initialization before the runner is called.
var test_plugin: Node

func _ready() -> void:
    get_tree().process_frame.connect(_on_frame, CONNECT_ONE_SHOT)

func _on_frame() -> void:
    test_plugin = GdextestPlugin.new()
    add_child(test_plugin)

func _exit_tree() -> void:
    if test_plugin:
        remove_child(test_plugin)
        test_plugin.queue_free()
        test_plugin = null
'''


def _godot_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _packed_strings(values: Iterable[str]) -> str:
    return "PackedStringArray(" + ", ".join(_godot_quote(v) for v in values) + ")"


def _manifest(entry_symbol: str, godot_version: str, library_key: str,
              library_basename: str) -> str:
    return f'''[configuration]

entry_symbol = {_godot_quote(entry_symbol)}
compatibility_minimum = {_godot_quote(godot_version)}

[libraries]

{library_key} = {_godot_quote("res://addons/gdextest/bin/" + library_basename)}
'''


def _project(project_name: str, godot_version: str,
             manifest_basename: str,
             native_extensions: Iterable[str],
             host_mode: str,
             extension_manifest: str | None = None) -> str:
    paths = [f"res://addons/gdextest/{manifest_basename}"]
    if extension_manifest:
        paths.append("res://addons/consumer/" + Path(extension_manifest).name)
    paths.extend(native_extensions)
    autoload = '' if host_mode == "editor" else '\n[autoload]\n\ngdextestHost="*res://addons/gdextest/runtime.gd"\n'
    plugins = ('\n[editor_plugins]\n\nenabled=' +
               _packed_strings(["res://addons/gdextest/plugin.cfg"]) + '\n'
               if host_mode == "editor" else '')
    return f'''; Generated by gdextest. Do not edit; this directory is disposable build output.

config_version=5

[application]

config/name={_godot_quote(project_name)}
config/features={_packed_strings([godot_version])}

[native_extensions]

paths={_packed_strings(paths)}

{plugins}{autoload}'''


def generate_fixture(*, project_root: str | os.PathLike[str], library_path: str | os.PathLike[str],
                     library_basename: str, manifest_basename: str,
                     entry_symbol: str = "gdextest_library_init",
                     plugin_class: str = "GdextestPlugin",
                     project_name: str = "gdextest fixture",
                     godot_version: str = "4.5",
                     library_key: str = "linux.debug.x86_64",
                     native_extensions: Iterable[str] = (),
                     extension_library: str | os.PathLike[str] | None = None,
                     extension_manifest: str | os.PathLike[str] | None = None,
                     fixture_assets: Iterable[str] = (),
                     host_mode: str = "editor",
                     project_source_root: str | os.PathLike[str] | None = None) -> None:
    """Create or refresh a generated fixture directory.

    `plugin_class` is accepted as part of the public generator contract. The
    built-in host currently uses `GdextestPlugin`; custom hosts can replace the
    generated wrapper in a later phase without changing the SCons API.
    """
    del plugin_class
    if host_mode not in {"editor", "runtime"}:
        raise ValueError(f"unsupported gdextest host mode: {host_mode}")
    root = Path(project_root)
    library = Path(library_path)
    addon = root / "addons" / "gdextest"
    binary_dir = addon / "bin"
    binary_dir.mkdir(parents=True, exist_ok=True)

    # Generated output may be reused with a different host mode.
    for stale in (addon / "plugin.cfg", addon / "plugin.gd", addon / "runtime.gd"):
        if stale.exists():
            stale.unlink()

    (root / "project.godot").write_text(
        _project(project_name, godot_version, manifest_basename, native_extensions, host_mode,
                 Path(extension_manifest).name if extension_manifest else None),
        encoding="utf-8")
    if host_mode == "editor":
        (addon / "plugin.cfg").write_text(PLUGIN_CFG, encoding="utf-8")
        (addon / "plugin.gd").write_text(EDITOR_PLUGIN_GD, encoding="utf-8")
    else:
        (addon / "runtime.gd").write_text(RUNTIME_PLUGIN_GD, encoding="utf-8")
    (addon / manifest_basename).write_text(
        _manifest(entry_symbol, godot_version, library_key, library_basename),
        encoding="utf-8")

    destination = binary_dir / library_basename
    if not library.is_file():
        raise FileNotFoundError(f"gdextest library does not exist: {library}")
    shutil.copy2(library, destination)

    if extension_library:
        extension = Path(extension_library)
        extension_destination = root / "addons" / "consumer" / "bin" / extension.name
        extension_destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(extension, extension_destination)
    if extension_manifest:
        manifest = Path(extension_manifest)
        manifest_destination = root / "addons" / "consumer" / manifest.name
        manifest_destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(manifest, manifest_destination)
    if project_source_root:
        copy_globbed_assets(Path(project_source_root), root, fixture_assets)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True, type=Path)
    parser.add_argument("--library", required=True, type=Path)
    parser.add_argument("--library-basename")
    parser.add_argument("--manifest-basename", default="gdextest.gdextension")
    parser.add_argument("--entry-symbol", default="gdextest_library_init")
    parser.add_argument("--project-name", default="gdextest fixture")
    parser.add_argument("--godot-version", default="4.5")
    parser.add_argument("--library-key", default="linux.debug.x86_64")
    parser.add_argument("--native-extension", action="append", default=[])
    parser.add_argument("--fixture-asset", action="append", default=[])
    parser.add_argument("--host-mode", choices=("editor", "runtime"), default="editor")
    args = parser.parse_args()
    basename = args.library_basename or args.library.name
    generate_fixture(
        project_root=args.project_root,
        library_path=args.library,
        library_basename=basename,
        manifest_basename=args.manifest_basename,
        entry_symbol=args.entry_symbol,
        project_name=args.project_name,
        godot_version=args.godot_version,
        library_key=args.library_key,
        native_extensions=args.native_extension,
        fixture_assets=args.fixture_asset,
        host_mode=args.host_mode,
        project_source_root=Path.cwd(),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
